# docker-compose file used to run services in single node, so the heart apps can be run directly from the IDE without problem
version: '3'
# from https://github.com/confluentinc/examples/blob/5.4.1-post/cp-all-in-one-community/docker-compose.yml
services:
  # ZOOKEEPERS ------------------------------------------------------------------------------------
  zk:
    image: confluentinc/cp-zookeeper:${CONFLUENT_TAG}
    container_name: zk
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  # KAFKAS ----------------------------------------------------------------------------------------
  kafka:
    image: confluentinc/cp-kafka:${CONFLUENT_TAG}
    container_name: kafka
    depends_on:
      - zk
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  # SCHEMA REGISTRY --------------------------------------------------------------------------------
  schema-registry:
    image: confluentinc/cp-schema-registry:${CONFLUENT_TAG}
    container_name: schema-registry
    depends_on:
      - zk
      - kafka
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zk:2181
