spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
    producer:
      # producer properties can be found in org.apache.kafka.clients.producer.ProducerConfig
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
  jackson:
    # ensure the input/output in epoch milli are correctly read/write by Jackson
    deserialization:
      READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
    serialization:
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  main:
    banner-mode: OFF
topic:
  name: heart-beats
  partitions: 1
  replicas: 1
server:
  port: 8082